structure:
  readme: docs/welcome.md
  summary: docs/README.md

redirects:
  installation: ./docs/basics/installation.md
  quick-start: ./docs/basics/quick-start.md
  stack-graph: ./docs/basics/stack-graph.md
  troubleshooting: ./docs/misc/troubleshooting.md
  examples/demo-project: ./docs/example-projects/demo-project.md
  examples/tls-project: ./docs/example-projects/tls-project.md
  examples/using-garden-in-ci: ./docs/example-projects/using-garden-in-ci.md
  guides/using-remote-sources: ./docs/advanced/using-remote-sources.md
  guides/cert-manager-integration: ./docs/advanced/cert-manager-integration.md
  providers/conftest-container: ./docs/reference/providers/conftest-container.md
  providers/conftest-kubernetes: ./docs/reference/providers/conftest-kubernetes.md
  providers/conftest: ./docs/reference/providers/conftest.md
  providers/hadolint: ./docs/reference/providers/hadolint.md
  providers/kubernetes: ./docs/reference/providers/kubernetes.md
  providers/local-kubernetes: ./docs/reference/providers/local-kubernetes.md
  providers/maven-container: ./docs/reference/providers/maven-container.md
  providers/openfaas: ./docs/reference/providers/openfaas.md
  providers/terraform: ./docs/reference/providers/terraform.md
  module-types/conftest: ./docs/reference/module-types/conftest.md
  module-types/container: ./docs/reference/module-types/container.md
  module-types/exec: ./docs/reference/module-types/exec.md
  module-types/hadolint: ./docs/reference/module-types/hadolint.md
  module-types/helm: ./docs/reference/module-types/helm.md
  module-types/kubernetes: ./docs/reference/module-types/kubernetes.md
  module-types/maven-container: ./docs/reference/module-types/maven-container.md
  module-types/openfaas: ./docs/reference/module-types/openfaas.md
  module-types/persistentvolumeclaim: ./docs/reference/module-types/persistentvolumeclaim.md
  module-types/terraform: ./docs/reference/module-types/terraform.md
